Feat/otp screen
RibonDAO/app pull request #744
Opened 2024-07-19 20:35 UTC by leodhb

# Description

- A brief description of the feature/fix

# Necessary changes

- Put here any changes that must be done when this PR is merged
- eg: update an environment variable

## Does this pull request close any open issues?

- Put here the issue that must be closed with this PR
- eg: closes [#001]()

## Did you use styled-components?

- [ ] Yes
- [ ] No

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Dangerous changes
- [ ] Chore (change that does not effect how the code works, eg: change color)
- [ ] Tests

## How to test

Put here all the things need to test this PR and verify your changes, also list any relevant details for tests (eg: have a wallet)

- Test A

2024-07-23 16:18 UTC, nathielymm requested changes

2024-07-23 16:18 UTC, nathielymm commented on src/screens/auth/InsertOtpCodeScreen/index.tsx
> +    <KeyboardAvoidingView
I think that this page needs a back arrow so the user could back to choose another way to authenticate  https://www.figma.com/design/lUEWCdGfmrdKzDPs8BeaHU/Autentica%C3%A7%C3%A3o?node-id=3295-9469&m=dev

2024-07-23 16:18 UTC, nathielymm commented on src/screens/auth/InsertOtpCodeScreen/styles.ts
> +  container: {
the screen is not centered, which could be weird on bigger devices 
![image](https://github.com/user-attachments/assets/52c2c0d2-db8a-407d-ac54-741dbdaf2723)

2024-07-24 13:44 UTC, leodhb commented on src/screens/auth/InsertOtpCodeScreen/styles.ts
> +  container: {
This screen, just like the e-mail screen is not centered vertically at all. Should we center the whole thing? I think it's because the Keyboard Avoid mechanic

2024-07-24 14:38 UTC, nathielymm approved these changes

2024-07-24 18:13 UTC, merged